server:
  port: 6031

spring:
  application:
    name: microservice-simple-config-server
  cloud:    config:      server:        git:
          uri: https://github.com/guessagithub/Spring-cloud-config-repo.git
          username: guessagithub
          password: 6212621a
                    
    

 